gems: [bourbon, bitters, neat]

# Site settings
title: The Link List
email: danielfosco@gmail.com
description:
baseurl: http://dfosco.github.io/linklist


# Structure configuration
source: source
destination: _site

assets:
  cachebust: soft

# Build settings
markdown: kramdown
